name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
  release:
    types:
      - created

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      ANKIT_MONGO_URI: mongodb://localhost:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  deploy-staging:
    needs: build-test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file for staging
        run: echo "ANKIT_MONGO_URI=${{ secrets.MONGO_URI }}" > .env

      - name: Deploy to staging server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.APP_DIR_STAGING }}
            git pull origin staging
            # Copy new .env file
            echo "ANKIT_MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            # Restart your app (example using pm2 or systemctl, adjust accordingly)
            pkill -f "python app.py" || true
            nohup python3 app.py > app.log 2>&1 &

  deploy-production:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file for production
        run: echo "ANKIT_MONGO_URI=${{ secrets.MONGO_URI }}" > .env

      - name: Deploy to production server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PRODUCTION }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.APP_DIR_PRODUCTION }}
            git pull origin main
            echo "ANKIT_MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            pkill -f "python app.py" || true
            nohup python3 app.py > app.log 2>&1 &
